"DatabaseProvider":
  "class": "\Athene\Core\Database\Database"
  "args": 
    "dsn": "mysql://localhost/minerva"
    "user": "sebi"
    "pass": "blubb"

"ORMapper":
  "class": "Athene\Core\Database\ORM\Mapper"
    
"SessionProvider":
  "class": "\Athene\Core\Session\SessionHandler"
    
"SessionHandler":
  "class": "\Athene\Core\Session\Handlers\NativeSessions"

"SystemConfig":
  "class": "\Zend_Config_Yaml"
  "args": 
    "yaml": "CHANGE_ME", 
    "section": "development", 
    "options": "yaml_decoder": ["sfYaml", "load"]
    
"YAMLProvider":
  "class": "\sfYamlParser"