"DatabaseProvider":
  "class": "dbFacile"
  "method": "open"
  "is_static": true 
  "args": ["mysql", "minerva", "root", ""]

"SessionProvider":
  "class": "SessionHandler"
    
"SessionHandler":
  "class": "NativeSessions"

"SystemConfig":
  "class": "Zend_Config_Yaml"
  "args": 
    "yaml": "CHANGE_ME", 
    "section": "development", 
    "options": "yaml_decoder": ["sfYaml", "load"]